import 'package:flutter/material.dart';

List<LinearGradient> gradients = [
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.green.shade200,
      Colors.green.shade300,
      Colors.green.shade500,
      Colors.green.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.blueAccent.shade100,
      Colors.blueAccent.shade200,
      Colors.blueAccent.shade400,
      Colors.blueAccent.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.greenAccent.shade100,
      Colors.greenAccent.shade200,
      Colors.greenAccent.shade400,
      Colors.greenAccent.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.brown.shade200,
      Colors.brown.shade300,
      Colors.brown.shade500,
      Colors.brown.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.redAccent.shade100,
      Colors.redAccent.shade200,
      Colors.redAccent.shade400,
      Colors.redAccent.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.deepOrange.shade200,
      Colors.deepOrange.shade300,
      Colors.deepOrange.shade500,
      Colors.deepOrange.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.blue.shade200,
      Colors.blue.shade300,
      Colors.blue.shade500,
      Colors.blue.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.indigoAccent.shade100,
      Colors.indigoAccent.shade200,
      Colors.indigoAccent.shade400,
      Colors.indigoAccent.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.blue.shade200,
      Colors.blue.shade300,
      Colors.blue.shade500,
      Colors.blue.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.lightGreen.shade100,
      Colors.lightGreen.shade200,
      Colors.lightGreen.shade400,
      Colors.lightGreen.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.lightGreen.shade200,
      Colors.lightGreen.shade300,
      Colors.lightGreen.shade500,
      Colors.lightGreen.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.grey.shade200,
      Colors.grey.shade300,
      Colors.grey.shade500,
      Colors.grey.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.purple.shade200,
      Colors.purple.shade300,
      Colors.purple.shade500,
      Colors.purple.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.limeAccent.shade100,
      Colors.limeAccent.shade200,
      Colors.limeAccent.shade400,
      Colors.limeAccent.shade700,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.lime.shade200,
      Colors.lime.shade300,
      Colors.lime.shade500,
      Colors.lime.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.yellow.shade100,
      Colors.yellow.shade200,
      Colors.yellow.shade300,
      Colors.yellow.shade400,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.brown.shade100,
      Colors.brown.shade200,
      Colors.brown.shade300,
      Colors.brown.shade400,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.lime.shade100,
      Colors.lime.shade200,
      Colors.lime.shade300,
      Colors.lime.shade400,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.purple.shade200,
      Colors.purple.shade300,
      Colors.purple.shade500,
      Colors.purple.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
  LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomCenter,
    colors: [
      Colors.brown.shade200,
      Colors.brown.shade300,
      Colors.brown.shade500,
      Colors.brown.shade500,
    ],
    stops: const [
      0.1,
      0.3,
      0.9,
      1.0,
    ],
  ),
];

List<String> images = [
  'assets/1.png',
  'assets/2.png',
  'assets/3.png',
  'assets/4.png',
  'assets/5.png',
  'assets/6.png',
  'assets/7.png',
  'assets/8.png',
  'assets/9.png',
  'assets/10.png',
  'assets/11.png',
  'assets/12.png',
  'assets/13.png',
  'assets/14.png',
  'assets/15.png',
  'assets/16.png',
  'assets/17.png',
  'assets/18.png',
  'assets/19.png',
  'assets/20.png',
];
